[Interface]
PrivateKey = qOlCzcdV6lcI1hmOciEKoC48dOFsdti22cpOFvzXskg=
ListenPort = 51820

[Peer]
PublicKey = 5mGyqwzY1uANV2pP+1VgXaQNHzmjJI8vC/A+F6hIbAw=
Endpoint = 38.180.145.235:51820
AllowedIPs = 0.0.0.0/0,::/0
PersistentKeepalive = 25
