[Interface]
PrivateKey = aNzfS87TYFLM8Tn52z2wkimD/JCQoy/dkHLegvMynWE=
ListenPort = 51820

[Peer]
PublicKey = Qd/mZgga1tAmqqqOYAZcprztX6hJMp7j+hvP81xYIXg=
# wg支持roaming
AllowedIPs = 0.0.0.0/0,::/0
#PersistentKeepalive = 2

#PostUp = iptables -A FORWARD -i server -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;sysctl -w net.ipv4.ip_forward=1
#PostDown = iptables -D FORWARD -i server -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
